{% set name = "Flask" %}
{% set version = "1.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0fbeb6180d383a9186d0d6ed954e0042ad9f18e0e8de088b2b419d526927d196

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - flask = flask.cli:main

requirements:
  host:
    - python >=3.5
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.5
    - click >=5.1,<8.0
    - itsdangerous >=0.24,<2.0
    - jinja2 >=2.10.1,<3.0
    - werkzeug >=0.15,<2.0

test:
  requires:
    - pip
  imports:
    - flask
    - flask.json
  commands:
    - flask --help
    - pip check

about:
  home: https://palletsprojects.com/p/flask
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  license_url: https://github.com/pallets/flask/blob/main/LICENSE.rst
  summary: A simple framework for building complex web applications.
  description: |
    Flask is a lightweight [WSGI](https://wsgi.readthedocs.io/) web application framework. It is designed
    to make getting started quick and easy, with the ability to scale up to
    complex applications. It began as a simple wrapper around [Werkzeug](https://werkzeug.palletsprojects.com/)
    and [Jinja](https://jinja.palletsprojects.com/) and has become one of the most popular Python web
    application frameworks.
    Flask offers suggestions, but doesn't enforce any dependencies or
    project layout. It is up to the developer to choose the tools and
    libraries they want to use. There are many extensions provided by the
    community that make adding new functionality easy.
  doc_url: https://flask.palletsprojects.com/
  dev_url: https://github.com/pallets/flask/

extra:
  recipe-maintainers:
    - goanpeca
    - nehaljwani
    - ukaratay
    - marcelotrevisani
    - xylar