{% set name = "flask" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5f873c5184c897c8d9d1b05df1e3d01b14910ce69607a117bd3277098a5836ac

build:
  number: 0
  skip: True  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  entry_points:
    - flask = flask.cli:main

requirements:
  host:
    - python
    - pip
    - flit-core <4
  run:
    - python
    - blinker >=1.9
    - click >=8.1.3
    - importlib-metadata >=3.6  # [py<310]
    - itsdangerous >=2.2
    - jinja2 >=3.1.2
    - werkzeug >=3.1
  run_constrained:
    - asgiref >=3.2

test:
  imports:
    - flask
    - flask.json
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - asgiref
    - greenlet  # [py<311]
    - python-dotenv
  commands:
    - flask --help
    - pip check
    - pytest -vv
  downstreams:
    # flask 3.1.0 works fine with the next downstreams packages:
    #- cubes 1.1
    #- flask-admin 1.6.1
    #- flask-apscheduler 1.12.4
    #- flask-bcrypt 1.0.1
    #- flask-compress 1.13
    #- flask-cors 3.0.10
    #- flask-json 0.4.0
    #- flask-login 0.6.3
    #- flask-restful 0.3.9
    #- flask-restx 1.3.0
    #- flask-session 0.4.0
    #- flask-socketio 5.3.1
    #- flask-sqlalchemy 3.1.1
    #- flask-wtf 1.2.1
    #- jupyter-dash 0.4.2
    #- mlflow 2.18.0
    #- moto 5.0.5
    #- prometheus_flask_exporter 0.22.4

    # Not working with the next packages:
    #- blaze 0.11.3  # deprecated

    # Update flask-babel to 4.0.0
    #- flask-babel 2.0.0

    # Update flask-openid to 1.3.1:
    # ImportError: cannot import name 'url_quote' from 'werkzeug.urls'
    #- flask-openid 1.3.0

    # Rebuild flask-swagger 0.2.14 to fix: ModuleNotFoundError: No module named 'pkg_resources'
    #- flask-swagger 0.2.14

    # Update to the latest
    #- locustio 0.14.6

    # Won't work with werkzeug >=2.1
    #- tranquilizer 0.9.2


about:
  home: https://palletsprojects.com/p/flask
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A simple framework for building complex web applications.
  description: |
    Flask is a lightweight [WSGI](https://wsgi.readthedocs.io/) web application framework. It is designed
    to make getting started quick and easy, with the ability to scale up to
    complex applications. It began as a simple wrapper around [Werkzeug](https://werkzeug.palletsprojects.com/)
    and [Jinja](https://jinja.palletsprojects.com/) and has become one of the most popular Python web
    application frameworks.
    Flask offers suggestions, but doesn't enforce any dependencies or
    project layout. It is up to the developer to choose the tools and
    libraries they want to use. There are many extensions provided by the
    community that make adding new functionality easy.
  doc_url: https://flask.palletsprojects.com/
  dev_url: https://github.com/pallets/flask/

extra:
  recipe-maintainers:
    - goanpeca
    - nehaljwani
    - ukaratay
    - marcelotrevisani
    - xylar
