travis:
  secure:
    BINSTAR_TOKEN: QcEMJvUFvzbYfzpE37FRCkFjt/Q24M1clryHh6NXIEHbOT7G4lc2YWpvDJNm67vTlWBWO2UMLiwJHq7S+UTFHODSZ7wAo1MQuUvCXw4lKWwxxCSl0qifop8UpY8gA432Kra+HsT56jsSbyqpBWyPnfpdXqOoXkaJwohsw5EACihj7jIGJAf0KPHkyACh62CgWDK+88gOmLXvehOF9pRFTOpngFQq3+WrDILKbtrAWHMAu9q6uujXR7CSCWltDvz+mjK7kVID/vp7XRtD/PNH8kYo4vCR9H03CeNSx+2tNYvQmr8+pZMBZ45Brc/j54kZAwkjg78LiNeD3JijTfNl9ACQ4AdU5GaAE58sdEJvdkt9iyJoQ//Oda/9AhA3RP3/mLmiRvpblOKxzY3ISiOnSrn0/QVdnqhxQfpCKt1tA/uR5/VSn71fehxb49BNhteQ5e1mhgvZh5McCKGUg70f3qMJqGAyRz8qvpam6JsrzXEuVTBDpzaqfSCLPG6IgMFUwiG2VQIDEiQcxe7cmiwG6w4DLCIBkqbij1Ay328mA5CGOeY8YEatAeiapQTBiIFIOf8CoMYv+jMvz/rdG8OQQQRYKaT7sqPowqe8Aei+EEuE/r4jMmof5frLP/2KAN+8feY1g2MxXkowEJmiuDvSa46B/Ys3Vo32BzOT4XMxi3A=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
